version: '3.5'
services:
  mysql_slave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "mysql-slave"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=Blitzcode1.
      - MYSQL_DATABASE=Blitzvideo
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password', '--skip-tls']
volumes:
  mysqldata:
